#!/bin/bash

if [ -d ${OPENSHIFT_DATADIR}/public/default ] && [ -d ${OPENSHIFT_DATADIR}/theme ] ; then
  GIT_WORK_TREE=${OPENSHIFT_DATADIR}/theme git pull
  pelican ${OPENSHIFT_REPO_DIR}/data -o ${OPENSHIFT_DATADIR}/public/default -s ${OPENSHIFT_REPO_DIR}/conf/dcnetconf.py -t ${OPENSHIFT_DATADIR}/theme
elif [ -d ${OPENSHIFT_DATADIR}/theme ] ; then
  mkdir -p $OPENSHIFT_DATADIR/public/default
  pelican ${OPENSHIFT_REPO_DIR}/data -o ${OPENSHIFT_DATADIR}/public/default -s ${OPENSHIFT_REPO_DIR}/conf/dcnetconf.py -t ${OPENSHIFT_DATADIR}/theme
elif [ -d ${OPENSHIFT_DATADIR}/public/default ] ; then
  git clone $https://github.com/darrelclute/dcnet-theme-svbhack $OPENSHIFT_DATADIR/theme
  pelican ${OPENSHIFT_REPO_DIR}/data -o ${OPENSHIFT_DATADIR}/public/default -s ${OPENSHIFT_REPO_DIR}/conf/dcnetconf.py -t ${OPENSHIFT_DATADIR}/theme
else
  mkdir -p $OPENSHIFT_DATADIR/public/default
  git clone $https://github.com/darrelclute/dcnet-theme-svbhack $OPENSHIFT_DATADIR/theme
  pelican ${OPENSHIFT_REPO_DIR}/data -o ${OPENSHIFT_DATADIR}/public/default -s ${OPENSHIFT_REPO_DIR}/conf/dcnetconf.py -t ${OPENSHIFT_DATADIR}/theme
fi
