#!/bin/bash

PELICAN_INPUT=${OPENSHIFT_REPO_DIR}/data
PELICAN_CONF=${OPENSHIFT_REPO_DIR}/conf/dcnetconf.py
SITE_DIRECTORY=${OPENSHIFT_DATADIR}/public/default
CONFIG_DIR=${OPENSHIFT_DATADIR}/conf
THEME_DIR=${OPENSHIFT_DATADIR}/theme
THEME_GIT=https://github.com/darrelclute/dcnet-theme-svbhack

if [ -d ${CONFIG_DIR} ] ; then
    cp -y ${OPENSHIFT_REPO_DIR}/conf/*.conf ${CONFIG_DIR}
else
    mkdir -p ${CONFIG_DIR}
    cp -y ${OPENSHIFT_REPO_DIR}/conf/*.conf ${CONFIG_DIR}
fi


sed -i -e "s@OPENSHIFT_INTERNAL_IP@$OPENSHIFT_PYTHON_IP@g" -e "s@OPENSHIFT_HOMEDIR@$OPENSHIFT_HOMEDIR@g" -e "s@OPENSHIFT_DATA_DIR@$OPENSHIFT_DATA_DIR@g" -e "s@OPENSHIFT_LOG_DIR@$OPENSHIFT_PYTHON_LOG_DIR@g" -e "s@CONFIG_DIR@$CONFIG_DIR@g" ${CONFIG_DIR}/*.conf

httpd -f ${CONFIG_DIR}/httpd.conf -k start

exit 0
