#!/bin/bash

if [ -d ${OPENSHIFT_DATADIR}/conf ] ; then
    cp -y ${OPENSHIFT_REPO_DIR}/conf/*.conf ${OPENSHIFT_DATADIR}/conf
else
    mkdir -p ${OPENSHIFT_DATADIR}/conf
    cp -y ${OPENSHIFT_REPO_DIR}/conf/*.conf ${OPENSHIFT_DATADIR}/conf
fi


sed -i -e "s@OPENSHIFT_INTERNAL_IP@$OPENSHIFT_PYTHON_IP@g" -e "s@OPENSHIFT_HOMEDIR@$OPENSHIFT_HOMEDIR@g" -e "s@OPENSHIFT_DATA_DIR@$OPENSHIFT_DATA_DIR@g" -e "s@OPENSHIFT_LOG_DIR@$OPENSHIFT_PYTHON_LOG_DIR@g" -e "s@CONFIG_DIR@${OPENSHIFT_DATADIR}/conf@g" ${OPENSHIFT_DATADIR}/conf/*.conf

httpd -f ${OPENSHIFT_DATADIR}/conf/httpd.conf -k start

exit 0
