#!/bin/bash

PELICAN_INPUT=${OPENSHIFT_REPO_DIR}/data
PELICAN_CONF=${OPENSHIFT_REPO_DIR}/conf/dcnetconf.py
SITE_DIRECTORY=${OPENSHIFT_DATADIR}/public/default
CONFIG_DIR=${OPENSHIFT_DATADIR}/conf
THEME_DIR=${OPENSHIFT_DATADIR}/theme
THEME_GIT=https://github.com/darrelclute/dcnet-theme-svbhack

httpd -f ${CONFIG_DIR}/httpd.conf -k stop

exit 0
